-- =========================================================
-- VCA PHILIPPINES CMS DEMO
-- STEP 4 - DATABASE SCHEMA
-- =========================================================


-- ---------------------------------------------------------
-- 1. HOMEPAGE CONTENT
-- Exactly one row is allowed: id = 1
-- ---------------------------------------------------------

create table public.homepage_content (
    id bigint primary key default 1
        constraint homepage_content_single_row check (id = 1),

    site_logo_url text not null default '',

    theme_primary_color text not null default '#233B82',
    theme_secondary_color text not null default '#98C2EC',
    theme_background_color text not null default '#FFFFFF',
    theme_text_color text not null default '#1F2937',

    theme_heading_font text not null default 'system-default',
    theme_body_font text not null default 'system-default',

    hero_eyebrow text not null default '',
    hero_title text not null default '',
    hero_description text not null default '',
    hero_image_url text not null default '',
    hero_button_text text not null default '',
    hero_button_link text not null default '',

    about_label text not null default '',
    about_title text not null default '',
    about_description text not null default '',
    about_image_url text not null default '',

    footer_text text not null default '',

    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),

    constraint homepage_primary_color_hex
        check (theme_primary_color ~ '^#[0-9A-Fa-f]{6}$'),

    constraint homepage_secondary_color_hex
        check (theme_secondary_color ~ '^#[0-9A-Fa-f]{6}$'),

    constraint homepage_background_color_hex
        check (theme_background_color ~ '^#[0-9A-Fa-f]{6}$'),

    constraint homepage_text_color_hex
        check (theme_text_color ~ '^#[0-9A-Fa-f]{6}$')
);


-- ---------------------------------------------------------
-- 2. HOMEPAGE ANNOUNCEMENTS / EVENTS
-- Multiple rows are allowed
-- ---------------------------------------------------------

create table public.homepage_announcements (
    id bigint generated by default as identity primary key,

    homepage_id bigint not null default 1
        references public.homepage_content(id)
        on delete cascade,

    announcement_date text not null default '',
    announcement_title text not null default '',
    announcement_description text not null default '',

    sort_order integer not null default 1
        check (sort_order >= 1),

    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);


-- ---------------------------------------------------------
-- 3. AUTOMATIC UPDATED_AT FUNCTION
-- ---------------------------------------------------------

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
    new.updated_at = now();
    return new;
end;
$$;


-- ---------------------------------------------------------
-- 4. UPDATED_AT TRIGGERS
-- ---------------------------------------------------------

create trigger set_homepage_content_updated_at
before update on public.homepage_content
for each row
execute function public.set_updated_at();


create trigger set_homepage_announcements_updated_at
before update on public.homepage_announcements
for each row
execute function public.set_updated_at();


-- ---------------------------------------------------------
-- 5. ROW LEVEL SECURITY
-- ---------------------------------------------------------

alter table public.homepage_content
enable row level security;

alter table public.homepage_announcements
enable row level security;


-- ---------------------------------------------------------
-- 6. PUBLIC READ POLICIES
-- Write policies will be added later with CMS authentication.
-- ---------------------------------------------------------

create policy "Public can read homepage content"
on public.homepage_content
for select
to anon, authenticated
using (true);


create policy "Public can read homepage announcements"
on public.homepage_announcements
for select
to anon, authenticated
using (true);
