import {fixture as db} from '/admin/js/supabase-client.js';
import {loadEditorContent,createEditorPersistence,mapHomepageRow} from '/admin/js/editor-data.js';
import {createEditorState,statesEqual} from '/admin/js/editor-state.js';
import {validateForSave} from '/admin/js/editor-validation.js';
const results=[];
const check=(name,ok)=>{if(!ok)throw Error(name);results.push(name);};
const el=id=>document.getElementById(id);
const click=id=>el(id+'-button').click();
const wait=ms=>new Promise(resolve=>setTimeout(resolve,ms));
async function until(test){for(let i=0;i<150;i++){if(test())return;await wait(10);}throw Error('Timed out');}
const writes=()=>db.calls.filter(c=>c.action!=='select');
function edit(id,value){el(id).value=value;el(id).dispatchEvent(new Event('input',{bubbles:true}));}
const submit=()=>el('homepage-editor-form').dispatchEvent(new Event('submit',{bubbles:true,cancelable:true}));
async function save(){submit();await until(()=>el('homepage-editor-form').getAttribute('aria-busy')==='false');}
try {
  await import('/admin/js/homepage-editor.js');
  await until(()=>el('hero-title').value==='Saved title');
  check('Initial load and clean controls',el('undo-button').disabled&&el('redo-button').disabled&&el('cancel-button').disabled&&el('save-button').disabled);
  const cards=()=>[...document.querySelectorAll('.announcement-entry')];
  const toggle=index=>cards()[index].querySelector('[data-edit-announcement]').click();
  const locked=index=>[...cards()[index].querySelectorAll('input,textarea')].every(input=>input.readOnly);
  const originalTitle=cards()[0].querySelector('[data-field="announcement_title"]').value;
  const initialWrites=writes().length;
  check('Loaded announcement fields protected',locked(0)&&cards()[0].querySelector('[data-edit-announcement]').textContent==='Edit');
  toggle(0);
  check('Edit mode alone creates no history or writes',!locked(0)&&el('undo-button').disabled&&el('cancel-button').disabled&&writes().length===initialWrites);
  edit(cards()[0].querySelector('[data-field="announcement_title"]').id,'Unsaved safety edit');toggle(0);
  check('Done Editing locks and retains unsaved value',locked(0)&&cards()[0].querySelector('[data-field="announcement_title"]').value==='Unsaved safety edit'&&!el('undo-button').disabled&&db.rows[0].announcement_title===originalTitle&&writes().length===initialWrites);
  click('undo');check('Edit mode toggles add no extra history',el('undo-button').disabled&&locked(0)&&cards()[0].querySelector('[data-field="announcement_title"]').value===originalTitle);
  click('redo');check('Redo preserves locked UI and edited value',locked(0)&&cards()[0].querySelector('[data-field="announcement_title"]').value==='Unsaved safety edit');
  window.confirm=()=>true;click('cancel');
  check('Cancel restores saved title and protection',locked(0)&&cards()[0].querySelector('[data-field="announcement_title"]').value===originalTitle&&el('undo-button').disabled&&el('redo-button').disabled);
  click('add-announcement');check('New announcement starts editable',!locked(1)&&locked(0));
  toggle(1);toggle(0);check('Edit unlocks only selected card',!locked(0)&&locked(1));toggle(0);
  const historyBefore=[el('undo-button').disabled,el('redo-button').disabled];
  window.confirm=()=>false;cards()[1].querySelector('[data-delete-announcement]').click();
  check('Declined new-row delete preserves history and card',cards().length===2&&String(historyBefore)===String([el('undo-button').disabled,el('redo-button').disabled])&&writes().length===initialWrites);
  window.confirm=()=>true;cards()[1].querySelector('[data-delete-announcement]').click();click('undo');
  check('Confirmed new-row delete is undoable without writes',cards().length===2&&locked(1)&&writes().length===initialWrites);
  click('cancel');
  window.confirm=()=>false;cards()[0].querySelector('[data-delete-announcement]').click();
  check('Declined persisted delete makes no history',cards().length===1&&el('undo-button').disabled&&el('cancel-button').disabled);
  window.confirm=()=>true;cards()[0].querySelector('[data-delete-announcement]').click();
  check('Confirmed persisted delete stays browser-only',cards().length===0&&db.rows.length===1&&writes().length===initialWrites);
  click('undo');check('Undo restores persisted card protected',cards().length===1&&locked(0));
  toggle(0);click('restore-default');
  check('Defaults show functional protected controls',locked(0));toggle(0);check('Default card can be edited',!locked(0));click('undo');
  check('Undo defaults restores prior edit mode',!locked(0)&&cards()[0].querySelector('[data-field="announcement_title"]').value===originalTitle&&writes().length===initialWrites);
  toggle(0);
  edit('hero-title','Saved B');await save();
  check('Homepage text persisted',db.home.hero_title==='Saved B'&&el('editor-status').textContent.includes('successfully'));
  check('Successful Save history boundary',el('undo-button').disabled&&el('redo-button').disabled&&el('cancel-button').disabled);
  edit('hero-title','Saved C');edit('footer-text','Footer C');edit('theme_primary_color','#123456');await save();
  check('Multiple fields persisted',db.home.hero_title==='Saved C'&&db.home.footer_text==='Footer C'&&db.home.theme_primary_color==='#123456');
  click('add-announcement');let title=document.querySelectorAll('[data-field="announcement_title"]')[1];edit(title.id,'New event');
  const before=writes().length;submit();submit();submit();
  check('Saving locks editing and history',el('hero-title').disabled&&el('undo-button').disabled&&el('save-button').disabled);
  await until(()=>!el('hero-title').disabled);
  check('Add announcement and duplicate submit prevention',db.rows.length===2&&writes().slice(before).filter(c=>c.action==='insert').length===1);
  const id=db.rows.find(r=>r.announcement_title==='New event').id;
  document.querySelectorAll('[data-edit-announcement]')[1].click();
  title=document.querySelectorAll('[data-field="announcement_title"]')[1];edit(title.id,'Edited event');
  document.querySelectorAll('[data-edit-announcement]')[1].click();await save();
  check('Edit announcement retains generated identity',db.rows.length===2&&db.rows.find(r=>r.id===id).announcement_title==='Edited event');
  window.confirm=()=>true;document.querySelector('[data-delete-announcement]').click();
  check('Delete is deferred until Save',db.rows.length===2);await save();
  check('Delete persisted and order normalized',db.rows.length===1&&db.rows[0].id===id&&db.rows[0].sort_order===1);
  const frame=document.createElement('iframe');frame.src='/reload-fixture';document.body.append(frame);await new Promise(resolve=>frame.onload=resolve);
  await until(()=>frame.contentDocument.getElementById('hero-title').value==='Saved C');
  check('Fresh reload from fixture database',frame.contentDocument.getElementById('footer-text').value==='Footer C'&&frame.contentDocument.querySelectorAll('.announcement-entry').length===1&&frame.contentDocument.querySelector('[data-field="announcement_title"]').value==='Edited event');
  frame.remove();
  let count=writes().length;edit('hero-title','');await save();
  check('Validation stops all writes and retains history',writes().length===count&&!el('undo-button').disabled&&el('hero-title').value==='');click('undo');
  edit('hero-title','Retry me');edit('footer-text','Redo survives');click('undo');
  db.fail={table:'homepage_content',action:'update',after:1};await save();
  check('Failed Save preserves both history stacks and edits',el('hero-title').value==='Retry me'&&!el('undo-button').disabled&&!el('redo-button').disabled&&!el('save-button').disabled);
  click('undo');check('Failed Save did not advance baseline',el('hero-title').value==='Saved C'&&el('cancel-button').disabled);click('redo');await save();
  check('Failed Save is retryable',db.home.hero_title==='Retry me'&&el('undo-button').disabled);
  const transfer=new DataTransfer();transfer.items.add(new File(['image'],'local.png',{type:'image/png'}));el('hero-image-input').files=transfer.files;el('hero-image-input').dispatchEvent(new Event('change',{bubbles:true}));
  const preview=el('hero-image-preview').src;count=writes().length;
  db.uploadFail={after:1};await save();
  check('Failed pending upload blocks writes without losing preview',writes().length===count&&el('hero-image-preview').src===preview&&!el('undo-button').disabled);click('undo');
  // Exercise real persistence service with isolated state and controlled failures.
  const state=createEditorState(await loadEditorContent());const service=createEditorPersistence();
  const first=state.addAnnouncement();state.setAnnouncement(first,'announcement_title','First insert');
  const second=state.addAnnouncement();state.setAnnouncement(second,'announcement_title','Second insert');
  const snapshot=state.currentState,baseline=state.savedState;
  db.fail={table:'homepage_announcements',action:'insert',after:2};
  await service.save(snapshot,baseline).then(()=>{throw Error('Expected failure');},()=>{});
  check('Partial failure leaves complete state and baseline intact',statesEqual(snapshot,state.currentState)&&statesEqual(baseline,state.savedState)&&state.canUndo&&service.hasPendingWrites);
  let persisted=await service.save(snapshot,baseline);state.acceptSavedState(persisted);service.acknowledge();
  check('Partial retry does not duplicate acknowledged insert',db.rows.filter(r=>r.announcement_title==='First insert').length===1&&db.rows.filter(r=>r.announcement_title==='Second insert').length===1&&state.currentState.announcements.every(r=>r.id));
  const lost=state.addAnnouncement();state.setAnnouncement(lost,'announcement_title','Lost response');
  db.fail={table:'homepage_announcements',action:'insert',after:1,afterWrite:true};
  await service.save(state.currentState,state.savedState).catch(()=>{});
  persisted=await service.save(state.currentState,state.savedState);state.acceptSavedState(persisted);service.acknowledge();
  check('Lost insert response reconciled without duplication',db.rows.filter(r=>r.announcement_title==='Lost response').length===1);
  // Save current array sequence, not stale sort_order values.
  const reordered=state.currentState;reordered.announcements.reverse();
  persisted=await service.save(reordered,state.savedState);state.acceptSavedState(persisted);service.acknowledge();
  const reloaded=await loadEditorContent();
  check('Ordering survives fresh service load',reloaded.announcements.map(r=>r.id).join()===reordered.announcements.map(r=>r.id).join());
  // A lost DELETE response followed by Undo must recover the deleted row on retry.
  const victim=state.currentState.announcements[0];state.deleteAnnouncement(victim.clientId);
  db.fail={table:'homepage_announcements',action:'delete',after:1,afterWrite:true};
  await service.save(state.currentState,state.savedState).catch(()=>{});state.undo();
  persisted=await service.save(state.currentState,state.savedState);state.acceptSavedState(persisted);service.acknowledge();
  check('Lost Delete response then Undo remains retryable',db.rows.some(r=>r.announcement_title===victim.announcement_title));
  state.restoreDefaults();const defaults=state.defaultState;
  count=writes().length;
  check('Restore Default does not persist before Save',state.isDefault());
  persisted=await service.save(state.currentState,state.savedState);state.acceptSavedState(persisted);service.acknowledge();
  check('Explicit Save of defaults replaces old announcements',db.rows.length===defaults.announcements.length&&db.rows[0].announcement_title===defaults.announcements[0].announcement_title);
  // Uncertain insert with no visible match must not retry the INSERT blindly.
  const uncertain=createEditorPersistence();const uncertainState=createEditorState(await loadEditorContent());
  const uncertainId=uncertainState.addAnnouncement();uncertainState.setAnnouncement(uncertainId,'announcement_title','Uncertain');
  db.fail={table:'homepage_announcements',action:'insert',after:1,afterWrite:true};
  await uncertain.save(uncertainState.currentState,uncertainState.savedState).catch(()=>{});
  const hidden=db.rows.pop();count=writes().length;
  await uncertain.save(uncertainState.currentState,uncertainState.savedState).catch(()=>{});
  check('Uncertain insert pauses writes until reconciled',writes().length===count);
  db.rows.push(hidden);await uncertain.save(uncertainState.currentState,uncertainState.savedState);
  check('Payload excludes editor metadata',!('media' in mapHomepageRow(state.currentState))&&writes().every(c=>!c.payload||(!('clientId' in c.payload)&&!('created_at' in c.payload)&&!('updated_at' in c.payload))));
  check('Singleton update only with explicit filter',writes().filter(c=>c.table==='homepage_content').every(c=>c.action==='update'&&c.filters.some(([k,v])=>k==='id'&&v===1))&&db.home.id===1);
  const bad=state.currentState;bad.announcements[0].sort_order=0;check('Malformed ordering rejected',validateForSave(bad).length>0);
  db.user=false;count=writes().length;await service.save(state.currentState,state.savedState).catch(()=>{});
  check('Unauthenticated Save rejected before writes (fixture)',writes().length===count);db.user=true;
  const home=db.home;db.home=null;let missing=false;await loadEditorContent().catch(()=>{missing=true;});db.home=home;
  check('Missing singleton fails load without insertion',missing);
  count=writes().length;window.confirm=()=>true;click('restore-default');click('undo');click('redo');click('cancel');
  check('History controls never write',writes().length===count);
  check('No uncaught errors or import failures',!window.testErrors.length);
  document.body.innerHTML='<pre id="test-results">PASS\n'+results.join('\n')+'</pre>';
}catch(error){document.body.innerHTML='<pre id="test-results">FAIL\n'+error.stack+'\nPassed: '+results.join(', ')+'</pre>';}
